BootstrapPrototyping::Application.routes.draw do

  get 'ajax/switch_mode'
  
  match 'candidate_signup'                      => 'shareable#candidate_signup'
  match 'candidate_profile'                     => 'shareable#candidate_profile'
  match 'candidate_profile_public'              => 'shareable#candidate_profile_public'
  match 'candidate_profile_you_email'           => 'shareable#candidate_profile_you_email'
  match 'candidate_profile_you_social'          => 'shareable#candidate_profile_you_social'
  match 'candidate_profile_others'              => 'shareable#candidate_profile_others'
  match 'candidate_profile_social_share_you'    => 'shareable#candidate_profile_social_share_you'
  match 'candidate_profile_email_share_you'     => 'shareable#candidate_profile_email_share_you'
  match 'candidate_profile_social_share_others' => 'shareable#candidate_profile_social_share_others'
  match 'candidate_profile_email_share_others'  => 'shareable#candidate_profile_email_share_others'
  match 'candidate_conversations'               => 'shareable#candidate_conversations'
  match 'candidate_conversations2'              => 'shareable#candidate_conversations2'
  match 'candidate_conversations3'              => 'shareable#candidate_conversations3'
  match 'candidate_conversations4'              => 'shareable#candidate_conversations4'
  match 'candidate_sharings'                    => 'shareable#candidate_sharings'
  match 'candidate_sharings2'                   => 'shareable#candidate_sharings2'
  match 'candidate_sharings3'                   => 'shareable#candidate_sharings3'
  match 'candidate_matches'                     => 'shareable#candidate_matches'
  match 'candidate_matches2'                    => 'shareable#candidate_matches2'
  match 'candidate_matches3'                    => 'shareable#candidate_matches3'
  match 'candidate_matches4'                    => 'shareable#candidate_matches4'
  match 'candidate_isnt_interested'             => 'shareable#candidate_isnt_interested'
  match 'candidate_says_yes'                    => 'shareable#candidate_says_yes'
  match 'candidate_says_no'                     => 'shareable#candidate_says_no'
  match 'recruiter_signup'                      => 'shareable#recruiter_signup'
  match 'recruiter_profile'                     => 'shareable#recruiter_profile'
  match 'recruiter_says_yes'                    => 'shareable#recruiter_says_yes'
  match 'recruiter_says_no'                     => 'shareable#recruiter_says_no'
  match 'recruiter_starts_discussion'           => 'shareable#recruiter_starts_discussion'
  match 'recruiter_isnt_interested'             => 'shareable#recruiter_isnt_interested'
  match 'recruiter_profile_1_public'            => 'shareable#recruiter_profile_1_public'
  match 'recruiter_profile_1_others'            => 'shareable#recruiter_profile_1_others'
  match 'recruiter_profile_1_you'               => 'shareable#recruiter_profile_1_you'
  match 'recruiter_profile_2_public'            => 'shareable#recruiter_profile_2_public'
  match 'recruiter_profile_3_public'            => 'shareable#recruiter_profile_3_public'
  match 'recruiter_profile_4_public'            => 'shareable#recruiter_profile_4_public'
  match 'recruiter_conversations'               => 'shareable#recruiter_conversations'
  match 'recruiter_conversations2'              => 'shareable#recruiter_conversations2'
  match 'recruiter_conversations3'              => 'shareable#recruiter_conversations3'
  match 'recruiter_conversations4'              => 'shareable#recruiter_conversations4'
  match 'recruiter_sharings'                    => 'shareable#recruiter_sharings'
  match 'recruiter_sharings2'                   => 'shareable#recruiter_sharings2'
  match 'recruiter_sharings3'                   => 'shareable#recruiter_sharings3'

  root :to => 'pages#dashboard'
end
